### PR TITLE
Add BLAKE2B

### PR DESCRIPTION
**Pull request by thebigb**
I modified an [openly licensed C# port](https://github.com/BLAKE2/BLAKE2/tree/master/csharp) of [BLAKE2B](https://blake2.net/) to fit the interface. I know the focus of this project is on non-cryptographic hash functions, but I thought I'd check if you're interested regardless.

### CODE REVIEW

**Comment by thebigb** [comment]
Okay, so I noticed I still have some things to straighten out:

- Fix the project file (NET45 appears broken)
- Hash size is in bits, not bytes
- I've noticed there is a standardized testing procedure for the algorithms; I'm going to rework the tests to comply

Expecting to push the changes soon.

**Comment by thebigb** [comment]
Previously mentioned things are fixed now.

**Comment by brandondahler** [comment]
Good work, I'll review and look into merging soon (though I am getting married in the next few days, so it'll be a few weeks if not in the next 1-4 days).  

In the mean time, since you are the first outside developer to work on the project, do you have any comments about the project setup as a whole from a developers point of view?  Anything you would recommend changing, documenting, etc?

Brandon

**Comment by thebigb** [comment]
Awesome, and congratulations!

In the mean time I've added some documentation (and fixed and unfixed an issue).

As for the comments:
- I'm pretty happy with the project structure and programming interface. No comments there.
- For the contributors section perhaps it would be nice to have some documentation on the UnifiedData interface. And a brief overview of steps to add a new hash to the project could be nice.
- Maybe add a skeleton project?
- A benchmark project to test hash performance would be nice for developers to help pick a hash and compare performance with native implementations.
- Okay, one comment for the programming interface, maybe it would be cool to add a kind of ForEachGroupParallelAsync method to the UnifiedData interface. It might help implement tree hash algorithms in the future. It will probably need different dynamics than the other ForEach methods, though.

Cheers, Bernardo

**Comment by brandondahler** [comment]
Thanks for your contribution! 

I ended up moving the state information from being inside the Blake2b instance itself into a private inner class whose instances local to the ComputeHashInternal functions.  This allowed me to remove the locks and make the Blake2b instance itself immutable to allow it and its member methods to be thread-safe.

Brandon

**Comment by brandondahler** [comment]
@thebigb Just wanted to let you know that this pull request has made it into release 1.6.1 that has now been deployed to NuGet as [Data.HashFunction.Blake2B](https://www.nuget.org/packages/System.Data.HashFunction.Blake2B/)

**Comment by thebigb** [comment]
Thanks for the heads up!

**Pull request merged**
